#!/bin/bash
# Run JOB through Neo (Marcus et al., VLDB 2019).
#
# Neo is an end-to-end neural query optimizer. Marcus et al. never released
# the official source. Two practical options:
#   1. Community reimplementation: https://github.com/KostasMparmparousis/Neo
#   2. Balsa (SIGMOD 2022) — supersedes Neo and is what most evaluations use
#      since 2022. See job_run_balsa.sh for that path.
#
# Neo's architecture:
#   1. Train Tree-CNN on plan-tree -> latency for a set of training queries.
#   2. At inference: enumerate candidate plans (greedy), score with the net,
#      emit the winner as a pg_hint_plan hint string.
#   3. Forward (SQL + hint) to PostgreSQL.
#
# Setup (one-time, CPU-only — no CUDA needed):
#   git clone https://github.com/KostasMparmparousis/Neo ~/neo
#   # Build PG with pg_hint_plan extension (e.g. PG14):
#   git clone https://github.com/ossc-db/pg_hint_plan ~/pg_hint_plan
#   cd ~/pg_hint_plan && make PG_CONFIG=~/neo_pg/inst/bin/pg_config install
#   # Initialize cluster on PORT 5501:
#   initdb -D ~/neo_pgdata
#   pg_ctl -D ~/neo_pgdata -o "-p 5501" start
#   echo "shared_preload_libraries = 'pg_hint_plan'" >> ~/neo_pgdata/postgresql.conf
#   pg_ctl -D ~/neo_pgdata restart
#   # CPU-only PyTorch:
#   pip install --index-url https://download.pytorch.org/whl/cpu torch
#   pip install -r ~/neo/requirements.txt
#   export CUDA_VISIBLE_DEVICES=""
#   # Train Neo on JOB train split (hours on CPU), then start the inference service.
#
# This script expects a side-channel: $HINTS_DIR/<query>.hint contains the
# pg_hint_plan hint string for that query, pre-generated by Neo's inference.

set -euo pipefail
cd "$(dirname "$0")"
source ./lib.sh

export PGPORT="${NEO_PORT:-5501}"
export PGDATA="${NEO_PGDATA:-$HOME/neo_pgdata}"
export INSTDIR="${NEO_INSTDIR:-$HOME/neo/inst/bin}"
DB="${1:-imdb}"
ITERS="${2:-$ITERS}"
METHOD="neo"
HINTS_DIR="${NEO_HINTS_DIR:-$HOME/neo/hints}"
PSQL="$INSTDIR/psql -p $PGPORT -d $DB -U $PGUSER -X -q"

mkdir -p "$PLANS_DIR/$METHOD" "$RESULTS_DIR" "$LOG_DIR"
OUT_CSV="$RESULTS_DIR/${METHOD}_job.csv"
csv_header > "$OUT_CSV"

if [ ! -d "$HINTS_DIR" ]; then
    echo "ERROR: $HINTS_DIR not found. Run Neo inference first to generate per-query hints." >&2
    exit 1
fi

# Apply hint to a query and time it
neo_run_once() {
    local qf="$1" hint_file="$2"
    {
        echo "LOAD 'pg_hint_plan';"
        echo "SET statement_timeout = ${STATEMENT_TIMEOUT_MS};"
        echo "\\timing on"
        [ -f "$hint_file" ] && cat "$hint_file"
        sed 's/;[[:space:]]*$//' "$qf"
        echo ";"
    } | $PSQL -f - 2>/dev/null \
        | awk '/^Time: / { print $2; exit }'
}

neo_save_explain() {
    local qf="$1" hint_file="$2" name plan_file
    name="$(basename "$qf" .sql)"
    plan_file="$PLANS_DIR/$METHOD/${name}.plan"
    {
        echo "LOAD 'pg_hint_plan';"
        echo "SET statement_timeout = ${STATEMENT_TIMEOUT_MS};"
        [ -f "$hint_file" ] && cat "$hint_file"
        echo "EXPLAIN"
        sed 's/;[[:space:]]*$//' "$qf"
        echo ";"
    } | $PSQL -f - > "$plan_file" 2>&1
}

queries=("$QUERY_FILES"/*.sql)
total=${#queries[@]}
for idx in "${!queries[@]}"; do
    qf="${queries[$idx]}"
    name="$(basename "$qf" .sql)"
    hint="$HINTS_DIR/${name}.hint"
    n=$((idx + 1))
    echo "[$n/$total] $name"

    neo_save_explain "$qf" "$hint"
    for i in $(seq 1 "$ITERS"); do
        ms=$(neo_run_once "$qf" "$hint")
        echo "$name,$i,${ms:-NA}" >> "$OUT_CSV"
    done
done

echo "Plans -> $PLANS_DIR/$METHOD"
echo "Times -> $OUT_CSV"
